fixtures:
  repositories:
    stdlib: '/Users/lepertoe/puppet/modules/ntp/spec/fixtures/modules/puppetlabs-stdlib'
      #repo: '/Users/lepertoe/puppet/modules/ntp/spec/fixtures/modules/puppetlabs-stdlib'
  symlinks:
    ntp: "#{source_dir}"
